---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: jammy
inputs:
- name: git-repo
outputs:
- name: test
run:
  path: git-repo/samples/simple/scripts/build-fail.sh